export const knowledgeTopics = [
  { id:"y-en-prepositions", title:"y 和 en 的区别看介词，不看中文", skill:"pronoms_y_en", level:"A2-B1", type:"grammar", summary:"y 通常替代 à + 地点/事物；en 通常替代 de + 名词或数量。先找介词和句法功能，再选择代词。", sections:[["一、最稳定的规则","y 替代 à、chez、dans、sur 等引出的地点，也可替代 à + 事物。en 替代 de + 名词、部分冠词以及不定数量。两者通常放在变位动词前。"],["二、判断四步","找被替代成分；看前面的介词；判断是人、地点、事物还是数量；把代词放回句子检查位置。不要从中文的“那里”“一些”直接反推。"],["三、涉及人物时停一下","à + 人通常用 lui/leur：Je parle à Marie → Je lui parle。de + 人常用重读人称代词：Je parle de Paul → Je parle de lui。"],["四、数量要保留","en 替代名词，但明确数量保留：J'ai trois livres → J'en ai trois。否定句：Je n'en ai pas。"],["五、考试陷阱","看到 à 就机械选 y；忽略先行词是人；把数量一起删除；复合时态中位置错误。正确形式如：J'y suis allé. J'en ai acheté deux."]], examples:[["Tu vas à la bibliothèque ? — Oui, j'y vais.","地点由 à 引出，所以用 y。"],["Tu penses à ton examen ? — Oui, j'y pense.","à + 事物，使用 y。"],["Tu veux du café ? — Oui, j'en veux.","部分冠词 du，使用 en。"],["Tu as beaucoup de travail ? — Oui, j'en ai beaucoup.","en 替代 de travail，数量保留。"]] },
  { id:"past-timeline", title:"过去时态先画时间轴，再看动作性质", skill:"temps_du_passe", level:"A2-B1", type:"grammar", summary:"背景和持续状态多用未完成过去时；完成事件用复合过去时；更早发生的动作使用愈过去时。", sections:[["未完成过去时","描述过去背景、习惯、持续状态或正在进行的动作。它回答“当时是什么状态/经常怎样”。"],["复合过去时","描述发生并完成、推动故事前进的事件。它回答“发生了什么”。"],["愈过去时","表示在另一个过去参照点之前已经完成：avoir/être 的 imparfait + 过去分词。"],["考试判断法","标出所有过去动作并确定参照点。不要只根据 hier、quand 选择；动作关系才决定答案。"]], examples:[["Il pleuvait quand je suis sorti.","下雨是背景，出门是事件。"],["Quand je suis arrivé, le film avait commencé.","电影开始早于我到达。"]] },
  { id:"reading-main-idea", title:"阅读主旨题不要被原文复现词诱导", skill:"idee_principale", level:"A2-B1", type:"reading", summary:"主旨答案要覆盖全文目的；只复述一个例子、数字或局部事实的选项通常是干扰项。", sections:[["主题与主旨","主题只是文章谈什么，主旨还包括作者围绕主题想说明什么。"],["一句话压缩全文","读完后先不看选项，用“作者通过……说明……”概括，再找范围和态度最匹配的答案。"],["四类干扰","范围过窄、范围过大、因果倒置、原文提到但并非重点。原词复现只是诱饵。"],["开头、转折和结尾","目的常在开头提出、结尾确认；转折后的内容通常更重要。"]], examples:[["La ville installe des fontaines pour réduire les bouteilles en plastique.","安装喷泉是措施，减少塑料垃圾才是主旨。"]] },
  { id:"connectors-structure", title:"连接词先判断逻辑，再判断后接结构", skill:"connecteurs", level:"B1", type:"grammar", summary:"先判断原因、结果、转折或让步，再检查后面是名词、不定式还是完整从句。", sections:[["让步","malgré + 名词；bien que + 虚拟式；même si + 直陈式。"],["原因","à cause de + 消极原因；grâce à + 积极原因；parce que + 从句。"],["目的","pour/afin de + 不定式；pour que/afin que + 虚拟式。"],["排除方法","先遮住选项判断逻辑，再看空格后的结构，最后比较语域。"]], examples:[["Malgré la pluie, ils sont sortis.","malgré 后接名词。"],["Bien qu'il pleuve, ils sortent.","bien que 后接虚拟式从句。"]] },
  { id:"listening-distractors", title:"听到原词不等于选项正确", skill:"ecoute_distracteurs", level:"A2-B1", type:"listening", summary:"听力干扰项常复用录音中的名词，但改变人物、动作、时间、否定或因果关系。", sections:[["先听关系","重点记录谁对谁做什么、什么时候、是否变化。"],["否定和修正","mais、finalement、en fait、ne...plus 后的信息常推翻前面。"],["不要过早作答","听到选项中的词后继续等待完整谓语和限定条件。"],["一次播放策略","读题预测场景；播放抓差异；结束后不要用常识补充录音。"]], examples:[["La réunion est maintenue, mais la présentation est reportée.","不能因为听到 reportée 就认为所有活动取消。"]] },
  { id:"si-condition", title:"si 条件句不能把两个“将来”直接放在一起", skill:"hypothese", level:"B1", type:"grammar", summary:"si + 现在时 → 现在/将来/命令式；si + 未完成过去时 → 条件式现在时。si 从句通常不用将来时或条件式。", sections:[["真实可能","Si + présent, présent/futur/impératif：Si tu viens, nous sortirons."],["现在假设","Si + imparfait, conditionnel présent：Si j'avais le temps, je voyagerais."],["常见错误","不要说 si j'aurai 或 si j'aurais。先确定 si 从句，再配另一半。"],["语义判断","现在时组合表示开放条件；imparfait + conditionnel 表示与现实有距离的设想。"]], examples:[["Si tu finis tôt, appelle-moi.","真实可能条件。"],["Si j'étais libre, je viendrais.","现在不真实或可能性较低。"]] }
];
export function getKnowledgeTopic(id){return knowledgeTopics.find(topic=>topic.id===id);}
